### ISSUE TITLE
对请求回来的JSON属性不熟悉找不到我需要的数据。

### ISSUE THREAD

**Issue by dowhilenet** [SherryDo/SherryWeather#10]
在 Today extension 里的 TodayViewController 文件中里面有个 结构体`TodayViewDataModel`初始化函数利用JOSN.

**Comment by dowhilenet** [comment]
打算自己去解析数据，反正数据也不是很多。不使用第三方库了。回头需要搞明白为什么有些库不能在 扩展应用中使用

**Comment by WangZhuo2015** [comment]
现在搞定了么

**Comment by dowhilenet** [comment]
正在解决

**Comment by dowhilenet** [comment]
搞定
