### ISSUE TITLE
Spot中code_d、code_n无法解析

### ISSUE THREAD

**Issue by WangZhuo2015** [SherryDo/SherryWeather#3]
Spot中code_d、code_n无法解析

**Comment by dowhilenet** [comment]
`init(cityName:String,dayForcast:JSON)` 

我把这里的参数修改为了 SwiftyJOSN 中定义的` JSON`类型 。

我认为在  使用SwiftyJSON的的成中不要随意的确定类型，除非到最后你找到了你想要的类型。

**Comment by dowhilenet** [comment]
可以尝试尝试其他的库，每个都有自己的优点。
